using UnityEngine;
using System.Collections;
using System.Collections.Generic;

namespace Constants
{
    public enum ElementType
    {
        Unset,
        Generic,
        Fire,
        Water,
        Electric,
        Brain,
        Germ,
        Weed,
        Heart,
        Soul,
        Dragon,
        Ghost,
        Pog,
        Meme,
        God,
        Armored
    }

    public enum DamageMultiplier
    {
        Negated,
        Ineffective,
        Normal,
        Effective,
        Critical,
        Supercritical
    }

    public static class Elements
    {

        public static Dictionary<ElementType, string> elementIcons = new Dictionary<ElementType, string>
        {
            { ElementType.Generic, "" },
            { ElementType.Fire, "🔥" },
            { ElementType.Water, "💧" },
            { ElementType.Electric, "⚡" },
            { ElementType.Brain, "🧠" },
            { ElementType.Germ, "🦠" },
            { ElementType.Weed, "🍁" },
            { ElementType.Heart, "💖" },
            { ElementType.Soul, "🕴" },
            { ElementType.Dragon, "🐉" },
            { ElementType.Ghost, "👻" },
            { ElementType.Pog, "🕶" },
            { ElementType.Meme, "🃏" },
            { ElementType.God, "🙏" },
            { ElementType.Armored, "🛡" },
        };

        public static Dictionary<ElementType, string> elementAbbreviations = new Dictionary<ElementType, string>
        {
            { ElementType.Generic, "" },
            { ElementType.Fire, "FIRE" },
            { ElementType.Water, "WATER" },
            { ElementType.Electric, "ELEC" },
            { ElementType.Brain, "BRAIN" },
            { ElementType.Germ, "GERM" },
            { ElementType.Weed, "WEED" },
            { ElementType.Heart, "HEART" },
            { ElementType.Soul, "SOUL" },
            { ElementType.Dragon, "DRAGN" },
            { ElementType.Pog, "POG" },
            { ElementType.Meme, "MEME" },
            { ElementType.God, "GOD" },
            { ElementType.Armored, "ARM" },
        };

        /**
         * The first key is the attacker's type.
         * The second key is the receiver's type.
         */
        public static Dictionary<ElementType, Dictionary<ElementType, DamageMultiplier>> elementMatrix = new Dictionary<ElementType, Dictionary<ElementType, DamageMultiplier>>()
        {
            [ElementType.Generic] = new Dictionary<ElementType, DamageMultiplier> { 
                [ElementType.Generic] = DamageMultiplier.Normal,
                [ElementType.Fire] = DamageMultiplier.Normal,
                [ElementType.Water] = DamageMultiplier.Normal,
                [ElementType.Electric] = DamageMultiplier.Normal,
                [ElementType.Brain] = DamageMultiplier.Normal,
                [ElementType.Germ] = DamageMultiplier.Normal,
                [ElementType.Weed] = DamageMultiplier.Normal,
                [ElementType.Heart] = DamageMultiplier.Normal,
                [ElementType.Soul] = DamageMultiplier.Normal,
                [ElementType.Dragon] = DamageMultiplier.Normal,
                [ElementType.Ghost] = DamageMultiplier.Normal,
                [ElementType.Pog] = DamageMultiplier.Normal,
                [ElementType.Meme] = DamageMultiplier.Normal,
                [ElementType.God] = DamageMultiplier.Negated,
                [ElementType.Armored] = DamageMultiplier.Ineffective,
            },
            [ElementType.Fire] = new Dictionary<ElementType, DamageMultiplier>
            {
                [ElementType.Generic] = DamageMultiplier.Normal,
                [ElementType.Fire] = DamageMultiplier.Normal,
                [ElementType.Water] = DamageMultiplier.Negated,
                [ElementType.Electric] = DamageMultiplier.Normal,
                [ElementType.Brain] = DamageMultiplier.Normal,
                [ElementType.Germ] = DamageMultiplier.Critical,
                [ElementType.Weed] = DamageMultiplier.Critical,
                [ElementType.Heart] = DamageMultiplier.Normal,
                [ElementType.Soul] = DamageMultiplier.Ineffective,
                [ElementType.Dragon] = DamageMultiplier.Ineffective,
                [ElementType.Ghost] = DamageMultiplier.Effective,
                [ElementType.Pog] = DamageMultiplier.Ineffective,
                [ElementType.Meme] = DamageMultiplier.Supercritical,
                [ElementType.God] = DamageMultiplier.Negated,
                [ElementType.Armored] = DamageMultiplier.Ineffective,
            },
            [ElementType.Water] = new Dictionary<ElementType, DamageMultiplier>
            {
                [ElementType.Generic] = DamageMultiplier.Normal,
                [ElementType.Fire] = DamageMultiplier.Critical,
                [ElementType.Water] = DamageMultiplier.Normal,
                [ElementType.Electric] = DamageMultiplier.Negated,
                [ElementType.Brain] = DamageMultiplier.Normal,
                [ElementType.Germ] = DamageMultiplier.Critical,
                [ElementType.Weed] = DamageMultiplier.Supercritical,
                [ElementType.Heart] = DamageMultiplier.Normal,
                [ElementType.Soul] = DamageMultiplier.Ineffective,
                [ElementType.Dragon] = DamageMultiplier.Ineffective,
                [ElementType.Ghost] = DamageMultiplier.Ineffective,
                [ElementType.Pog] = DamageMultiplier.Ineffective,
                [ElementType.Meme] = DamageMultiplier.Supercritical,
                [ElementType.God] = DamageMultiplier.Negated,
                [ElementType.Armored] = DamageMultiplier.Ineffective,
            },
            [ElementType.Electric] = new Dictionary<ElementType, DamageMultiplier>
            {
                [ElementType.Generic] = DamageMultiplier.Normal,
                [ElementType.Fire] = DamageMultiplier.Normal,
                [ElementType.Water] = DamageMultiplier.Critical,
                [ElementType.Electric] = DamageMultiplier.Normal,
                [ElementType.Brain] = DamageMultiplier.Ineffective,
                [ElementType.Germ] = DamageMultiplier.Critical,
                [ElementType.Weed] = DamageMultiplier.Normal,
                [ElementType.Heart] = DamageMultiplier.Critical,
                [ElementType.Soul] = DamageMultiplier.Ineffective,
                [ElementType.Dragon] = DamageMultiplier.Ineffective,
                [ElementType.Ghost] = DamageMultiplier.Ineffective,
                [ElementType.Pog] = DamageMultiplier.Ineffective,
                [ElementType.Meme] = DamageMultiplier.Supercritical,
                [ElementType.God] = DamageMultiplier.Negated,
                [ElementType.Armored] = DamageMultiplier.Ineffective,
            },
            [ElementType.Brain] = new Dictionary<ElementType, DamageMultiplier>
            {
                [ElementType.Generic] = DamageMultiplier.Normal,
                [ElementType.Fire] = DamageMultiplier.Normal,
                [ElementType.Water] = DamageMultiplier.Normal,
                [ElementType.Electric] = DamageMultiplier.Normal,
                [ElementType.Brain] = DamageMultiplier.Normal,
                [ElementType.Germ] = DamageMultiplier.Effective,
                [ElementType.Weed] = DamageMultiplier.Negated,
                [ElementType.Heart] = DamageMultiplier.Ineffective,
                [ElementType.Soul] = DamageMultiplier.Critical,
                [ElementType.Dragon] = DamageMultiplier.Critical,
                [ElementType.Ghost] = DamageMultiplier.Supercritical,
                [ElementType.Pog] = DamageMultiplier.Ineffective,
                [ElementType.Meme] = DamageMultiplier.Negated,
                [ElementType.God] = DamageMultiplier.Negated,
                [ElementType.Armored] = DamageMultiplier.Ineffective,
            },
            [ElementType.Germ] = new Dictionary<ElementType, DamageMultiplier>
            {
                [ElementType.Generic] = DamageMultiplier.Normal,
                [ElementType.Fire] = DamageMultiplier.Negated,
                [ElementType.Water] = DamageMultiplier.Critical,
                [ElementType.Electric] = DamageMultiplier.Negated,
                [ElementType.Brain] = DamageMultiplier.Critical,
                [ElementType.Germ] = DamageMultiplier.Normal,
                [ElementType.Weed] = DamageMultiplier.Critical,
                [ElementType.Heart] = DamageMultiplier.Supercritical,
                [ElementType.Soul] = DamageMultiplier.Critical,
                [ElementType.Dragon] = DamageMultiplier.Normal,
                [ElementType.Ghost] = DamageMultiplier.Negated,
                [ElementType.Pog] = DamageMultiplier.Critical,
                [ElementType.Meme] = DamageMultiplier.Normal,
                [ElementType.God] = DamageMultiplier.Negated,
                [ElementType.Armored] = DamageMultiplier.Ineffective,
            },
            [ElementType.Weed] = new Dictionary<ElementType, DamageMultiplier>
            {
                [ElementType.Generic] = DamageMultiplier.Normal,
                [ElementType.Fire] = DamageMultiplier.Negated,
                [ElementType.Water] = DamageMultiplier.Negated,
                [ElementType.Electric] = DamageMultiplier.Normal,
                [ElementType.Brain] = DamageMultiplier.Supercritical,
                [ElementType.Germ] = DamageMultiplier.Normal,
                [ElementType.Weed] = DamageMultiplier.Normal,
                [ElementType.Heart] = DamageMultiplier.Ineffective,
                [ElementType.Soul] = DamageMultiplier.Effective,
                [ElementType.Dragon] = DamageMultiplier.Critical,
                [ElementType.Ghost] = DamageMultiplier.Ineffective,
                [ElementType.Pog] = DamageMultiplier.Supercritical,
                [ElementType.Meme] = DamageMultiplier.Critical,
                [ElementType.God] = DamageMultiplier.Negated,
                [ElementType.Armored] = DamageMultiplier.Ineffective,
            },
            [ElementType.Heart] = new Dictionary<ElementType, DamageMultiplier>
            {
                [ElementType.Generic] = DamageMultiplier.Normal,
                [ElementType.Fire] = DamageMultiplier.Normal,
                [ElementType.Water] = DamageMultiplier.Normal,
                [ElementType.Electric] = DamageMultiplier.Ineffective,
                [ElementType.Brain] = DamageMultiplier.Effective,
                [ElementType.Germ] = DamageMultiplier.Ineffective,
                [ElementType.Weed] = DamageMultiplier.Critical,
                [ElementType.Heart] = DamageMultiplier.Normal,
                [ElementType.Soul] = DamageMultiplier.Negated,
                [ElementType.Dragon] = DamageMultiplier.Critical,
                [ElementType.Ghost] = DamageMultiplier.Ineffective,
                [ElementType.Pog] = DamageMultiplier.Critical,
                [ElementType.Meme] = DamageMultiplier.Negated,
                [ElementType.God] = DamageMultiplier.Negated,
                [ElementType.Armored] = DamageMultiplier.Ineffective,
            },
            [ElementType.Soul] = new Dictionary<ElementType, DamageMultiplier>
            {
                [ElementType.Generic] = DamageMultiplier.Normal,
                [ElementType.Fire] = DamageMultiplier.Ineffective,
                [ElementType.Water] = DamageMultiplier.Ineffective,
                [ElementType.Electric] = DamageMultiplier.Ineffective,
                [ElementType.Brain] = DamageMultiplier.Critical,
                [ElementType.Germ] = DamageMultiplier.Ineffective,
                [ElementType.Weed] = DamageMultiplier.Effective,
                [ElementType.Heart] = DamageMultiplier.Critical,
                [ElementType.Soul] = DamageMultiplier.Normal,
                [ElementType.Dragon] = DamageMultiplier.Ineffective,
                [ElementType.Ghost] = DamageMultiplier.Critical,
                [ElementType.Pog] = DamageMultiplier.Critical,
                [ElementType.Meme] = DamageMultiplier.Negated,
                [ElementType.God] = DamageMultiplier.Negated,
                [ElementType.Armored] = DamageMultiplier.Ineffective,
            },
            [ElementType.Dragon] = new Dictionary<ElementType, DamageMultiplier>
            {
                [ElementType.Generic] = DamageMultiplier.Normal,
                [ElementType.Fire] = DamageMultiplier.Normal,
                [ElementType.Water] = DamageMultiplier.Ineffective,
                [ElementType.Electric] = DamageMultiplier.Ineffective,
                [ElementType.Brain] = DamageMultiplier.Ineffective,
                [ElementType.Germ] = DamageMultiplier.Critical,
                [ElementType.Weed] = DamageMultiplier.Ineffective,
                [ElementType.Heart] = DamageMultiplier.Critical,
                [ElementType.Soul] = DamageMultiplier.Critical,
                [ElementType.Dragon] = DamageMultiplier.Critical,
                [ElementType.Ghost] = DamageMultiplier.Critical,
                [ElementType.Pog] = DamageMultiplier.Supercritical,
                [ElementType.Meme] = DamageMultiplier.Normal,
                [ElementType.God] = DamageMultiplier.Negated,
                [ElementType.Armored] = DamageMultiplier.Ineffective,
            },
            [ElementType.Ghost] = new Dictionary<ElementType, DamageMultiplier>
            {
                [ElementType.Generic] = DamageMultiplier.Normal,
                [ElementType.Fire] = DamageMultiplier.Ineffective,
                [ElementType.Water] = DamageMultiplier.Negated,
                [ElementType.Electric] = DamageMultiplier.Critical,
                [ElementType.Brain] = DamageMultiplier.Supercritical,
                [ElementType.Germ] = DamageMultiplier.Negated,
                [ElementType.Weed] = DamageMultiplier.Effective,
                [ElementType.Heart] = DamageMultiplier.Critical,
                [ElementType.Soul] = DamageMultiplier.Critical,
                [ElementType.Dragon] = DamageMultiplier.Effective,
                [ElementType.Ghost] = DamageMultiplier.Normal,
                [ElementType.Pog] = DamageMultiplier.Normal,
                [ElementType.Meme] = DamageMultiplier.Normal,
                [ElementType.God] = DamageMultiplier.Negated,
                [ElementType.Armored] = DamageMultiplier.Ineffective,
            },
            [ElementType.Pog] = new Dictionary<ElementType, DamageMultiplier>
            {
                [ElementType.Generic] = DamageMultiplier.Normal,
                [ElementType.Fire] = DamageMultiplier.Critical,
                [ElementType.Water] = DamageMultiplier.Critical,
                [ElementType.Electric] = DamageMultiplier.Critical,
                [ElementType.Brain] = DamageMultiplier.Critical,
                [ElementType.Germ] = DamageMultiplier.Ineffective,
                [ElementType.Weed] = DamageMultiplier.Ineffective,
                [ElementType.Heart] = DamageMultiplier.Critical,
                [ElementType.Soul] = DamageMultiplier.Ineffective,
                [ElementType.Dragon] = DamageMultiplier.Ineffective,
                [ElementType.Ghost] = DamageMultiplier.Ineffective,
                [ElementType.Pog] = DamageMultiplier.Normal,
                [ElementType.Meme] = DamageMultiplier.Supercritical,
                [ElementType.God] = DamageMultiplier.Negated,
                [ElementType.Armored] = DamageMultiplier.Ineffective,
            },
            [ElementType.Meme] = new Dictionary<ElementType, DamageMultiplier>
            {
                [ElementType.Generic] = DamageMultiplier.Normal,
                [ElementType.Fire] = DamageMultiplier.Negated,
                [ElementType.Water] = DamageMultiplier.Negated,
                [ElementType.Electric] = DamageMultiplier.Negated,
                [ElementType.Brain] = DamageMultiplier.Supercritical,
                [ElementType.Germ] = DamageMultiplier.Negated,
                [ElementType.Weed] = DamageMultiplier.Critical,
                [ElementType.Heart] = DamageMultiplier.Critical,
                [ElementType.Soul] = DamageMultiplier.Supercritical,
                [ElementType.Dragon] = DamageMultiplier.Negated,
                [ElementType.Ghost] = DamageMultiplier.Negated,
                [ElementType.Pog] = DamageMultiplier.Ineffective,
                [ElementType.Meme] = DamageMultiplier.Negated,
                [ElementType.God] = DamageMultiplier.Negated,
                [ElementType.Armored] = DamageMultiplier.Ineffective,
            },
            [ElementType.Armored] = new Dictionary<ElementType, DamageMultiplier>
            {
                [ElementType.Generic] = DamageMultiplier.Normal,
                [ElementType.Fire] = DamageMultiplier.Normal,
                [ElementType.Water] = DamageMultiplier.Normal,
                [ElementType.Electric] = DamageMultiplier.Normal,
                [ElementType.Brain] = DamageMultiplier.Normal,
                [ElementType.Germ] = DamageMultiplier.Normal,
                [ElementType.Weed] = DamageMultiplier.Normal,
                [ElementType.Heart] = DamageMultiplier.Normal,
                [ElementType.Soul] = DamageMultiplier.Normal,
                [ElementType.Dragon] = DamageMultiplier.Normal,
                [ElementType.Ghost] = DamageMultiplier.Normal,
                [ElementType.Pog] = DamageMultiplier.Normal,
                [ElementType.Meme] = DamageMultiplier.Normal,
                [ElementType.God] = DamageMultiplier.Negated,
                [ElementType.Armored] = DamageMultiplier.Ineffective,
            },
            [ElementType.God] = new Dictionary<ElementType, DamageMultiplier>
            {
                [ElementType.Generic] = DamageMultiplier.Critical,
                [ElementType.Fire] = DamageMultiplier.Critical,
                [ElementType.Water] = DamageMultiplier.Critical,
                [ElementType.Electric] = DamageMultiplier.Critical,
                [ElementType.Brain] = DamageMultiplier.Critical,
                [ElementType.Germ] = DamageMultiplier.Critical,
                [ElementType.Weed] = DamageMultiplier.Critical,
                [ElementType.Heart] = DamageMultiplier.Critical,
                [ElementType.Soul] = DamageMultiplier.Critical,
                [ElementType.Dragon] = DamageMultiplier.Critical,
                [ElementType.Ghost] = DamageMultiplier.Critical,
                [ElementType.Pog] = DamageMultiplier.Critical,
                [ElementType.Meme] = DamageMultiplier.Critical,
                [ElementType.God] = DamageMultiplier.Critical,
                [ElementType.Armored] = DamageMultiplier.Critical,
            },
        };
    }
}
